---
title: "postgres_practice"
format: html
editor: visual
---

## Postgres Practice

```{r}
library(tidyverse)
library(RPostgreSQL)
library(RPostgres)
library(rpostgis)
library(DBI)
library(sf)
library(here)
library(data.table)
```

OK, now for a database connection

```{r}
db <- "geodata"  #provide the name of your db
host_db <- "localhost" #i.e. # i.e. 'ec2-54-83-201-96.compute-1.amazonaws.com'
db_port <- "5432"  # or any other port specified by the DBA
db_user <- "postgres"  
db_password <- "postgres"

con <- dbConnect(RPostgres::Postgres(), dbname = db, host=host_db, port=db_port, user=db_user, password=db_password) 

#check connection
dbListTables(con)
```

Read some data in to R:

```{r}
buildingheights <- dbReadTable(con, "buildingheights1")

```

Test Write some data:

```{r}
dbWriteTable(con, name="build_ht", value=buildingheights, overwrite=TRUE)
```

Bit of data manipulation

```{r}
filenames <- list.files("../Download_BrightonBuildingHeight_2158450/mastermap_building_heights_4844182/tq/", pattern="*.csv", full.names=TRUE)

BHA_header <- read_csv("../Download_BrightonBuildingHeight_2158450/mastermap_building_heights_4844182/docs/BHA_Header.csv")

#put the column headers into a list
oldnames=list(names(BHA_header))

#read all csvs into single building heights dataframe
all_building_heights <- read_csv(filenames, id = "file_name", col_names = F)

#set column headers
setnames(all_building_heights, old = 2:11, new = c("OS_TOPO_TOID", "OS_TOPO_TOID_VERSION","BHA_ProcessDate","TileRef","AbsHMin","AbsH2","AbsHMax","RelH2","RelHMax","BHA_Conf"))
```

Read height data back into database

```{r}
dbWriteTable(con, name="all_building_heights", value=all_building_heights, overwrite=TRUE)
```
